### ISSUE TITLE
1.16 incompatible

### ISSUE THREAD

**Issue by x9nico** [magnusulf/MassiveCore#7]
## Affected Plugin

- **Affected Plugin Name:** MassiveCore
- **Affected Plugin Version:** 1.16.x

## Describe your Environment

- **Server Version:** Paper 1.16.1 (latest build)

## Steps to Reproduce this Bug

1. First I did this.
Start server
2. Next I did that.
Errors (incompatible):
[14:50:39] [Server thread/ERROR]: Error occurred while enabling MassiveCore v3.3.0 (Is it up to date?)
java.lang.NoSuchFieldError: VERSION_1_1
	at com.massivecraft.massivecore.command.type.enumeration.TypeWorldType.getNamesInner(TypeWorldType.java:35) ~[?:?]
	at com.massivecraft.massivecore.command.type.enumeration.TypeWorldType.getNamesInner(TypeWorldType.java:8) ~[?:?]
	at com.massivecraft.massivecore.command.type.TypeAbstract.getNames(TypeAbstract.java:310) ~[?:?]
	at com.massivecraft.massivecore.command.type.TypeAbstractChoice.createOptionKeys(TypeAbstractChoice.java:359) ~[?:?]
	at com.massivecraft.massivecore.command.type.TypeAbstractChoice.createOptions(TypeAbstractChoice.java:339) ~[?:?]
	at com.massivecraft.massivecore.command.type.TypeAbstractChoice.setAll(TypeAbstractChoice.java:77) ~[?:?]
	at com.massivecraft.massivecore.command.type.TypeAbstractChoice.setAll(TypeAbstractChoice.java:84) ~[?:?]
	at com.massivecraft.massivecore.command.type.enumeration.TypeEnum.<init>(TypeEnum.java:25) ~[?:?]
	at com.massivecraft.massivecore.command.type.enumeration.TypeWorldType.<init>(TypeWorldType.java:18) ~[?:?]
	at com.massivecraft.massivecore.command.type.enumeration.TypeWorldType.<clinit>(TypeWorldType.java:14) ~[?:?]
	at com.massivecraft.massivecore.command.type.RegistryType.registerAll(RegistryType.java:318) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.onEnableInner(MassiveCore.java:256) ~[?:?]
	at com.massivecraft.massivecore.MassivePlugin.onEnable(MassivePlugin.java:84) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]
[14:50:39] [Server thread/INFO]: [MassiveCore] Disabling MassiveCore v3.3.0
[14:50:39] [Server thread/INFO]: [MassiveCore 3.3.0] Disabled
[14:50:39] [Server thread/ERROR]: Error occurred while disabling MassiveCore v3.3.0 (Is it up to date?)
java.lang.NullPointerException: mconf
	at com.massivecraft.massivecore.MassiveCoreTaskDeleteFiles.run(MassiveCoreTaskDeleteFiles.java:24) ~[?:?]
	at com.massivecraft.massivecore.MassiveCore.onDisable(MassiveCore.java:399) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugin(CraftServer.java:500) ~[patched_1.16.1.jar:git-Paper-136]
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.enablePlugins(CraftServer.java:414) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:941) ~[patched_1.16.1.jar:git-Paper-136]
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-136]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_265]

**Comment by magnusulf** [comment]
This should be fixed in 6c89207
